"""Initial migration

Revision ID: ab560d9e3186
Revises: 
Create Date: 2025-07-24 13:20:47.754837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab560d9e3186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('experience_level', sa.String(length=64), nullable=True),
    sa.Column('cost_rate', sa.Float(), nullable=True),
    sa.Column('billing_rate', sa.Float(), nullable=True),
    sa.Column('utilization_percentage', sa.Float(), nullable=True),
    sa.Column('productivity_score', sa.Float(), nullable=True),
    sa.Column('bench_days', sa.Integer(), nullable=True),
    sa.Column('last_project_end_date', sa.String(length=32), nullable=True),
    sa.Column('primary_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('secondary_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('years_of_experience', sa.Float(), nullable=True),
    sa.Column('joining_date', sa.String(length=32), nullable=True),
    sa.Column('bench_start_date', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('billable_status', sa.Boolean(), nullable=True),
    sa.Column('utilization_rate', sa.Float(), nullable=True),
    sa.Column('project_success_rate', sa.Float(), nullable=True),
    sa.Column('performance_rating', sa.Integer(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('reporting_manager', sa.String(length=120), nullable=True),
    sa.Column('skill_category', sa.String(length=120), nullable=True),
    sa.Column('current_engagement', sa.String(length=120), nullable=True),
    sa.Column('project_name', sa.String(length=120), nullable=True),
    sa.Column('engagement_description', sa.String(length=255), nullable=True),
    sa.Column('engagement_start_date', sa.String(length=32), nullable=True),
    sa.Column('engagement_end_date', sa.String(length=32), nullable=True),
    sa.Column('aging_in_non_billable', sa.Integer(), nullable=True),
    sa.Column('current_bench_status', sa.Boolean(), nullable=True),
    sa.Column('engagement_detail', sa.String(length=255), nullable=True),
    sa.Column('is_intern', sa.Boolean(), nullable=True),
    sa.Column('internship_start_date', sa.String(length=32), nullable=True),
    sa.Column('internship_end_date', sa.String(length=32), nullable=True),
    sa.Column('assigned_project', sa.String(length=120), nullable=True),
    sa.Column('mentor_name', sa.String(length=120), nullable=True),
    sa.Column('stipend', sa.Float(), nullable=True),
    sa.Column('monthly_salary_cost', sa.Float(), nullable=True),
    sa.Column('monthly_revenue_generated', sa.Float(), nullable=True),
    sa.Column('cost_center', sa.String(length=120), nullable=True),
    sa.Column('total_ytd_cost', sa.Float(), nullable=True),
    sa.Column('total_ytd_revenue', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('escalations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=True),
    sa.Column('project', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('dateRaised', sa.String(length=32), nullable=True),
    sa.Column('resolutionETA', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=120), nullable=False),
    sa.Column('customer', sa.String(length=120), nullable=True),
    sa.Column('health_status', sa.String(length=32), nullable=True),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('on_time_percentage', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('dm_po', sa.String(length=120), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_employees',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'employee_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_employees')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('escalations')
    op.drop_table('employees')
    # ### end Alembic commands ###
