from ...presentation.extensions import db

class Finance(db.Model):
    __tablename__ = 'finance'
    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey('projects.id'))
    project_name = db.Column(db.String)
    project_type = db.Column(db.String)
    client = db.Column(db.String)
    sow_value = db.Column(db.Float)
    billing_rate = db.Column(db.Float)
    start_date = db.Column(db.String)
    end_date = db.Column(db.String)
    actual_cost_to_date = db.Column(db.Float)
    billable_resources = db.Column(db.Integer)
    non_billable_resources = db.Column(db.Integer)
    shadow_resources = db.Column(db.Integer)
    monthly_burn = db.Column(db.Float)
    projected_completion = db.Column(db.String)
    net_position = db.Column(db.Float)
    health_status = db.Column(db.String)
    profit_margin = db.Column(db.Float)
    utilization_rate = db.Column(db.Float)
    billable_cost = db.Column(db.Float)
    non_billable_cost = db.Column(db.Float)
    shadow_cost = db.Column(db.Float)
    finance_type = db.Column(db.String)
    finance_category = db.Column(db.String)
    finance_date = db.Column(db.Date)
    finance_notes = db.Column(db.String)
    revenue_generated = db.Column(db.Float)
    cost_center = db.Column(db.String)
    total_ytd_cost = db.Column(db.Float)
    total_ytd_revenue = db.Column(db.Float)
    # Add more fields as needed for analytics/reporting
