from ...presentation.extensions import db

class Intern(db.Model):
    __tablename__ = 'interns'
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.String)
    name = db.Column(db.String, nullable=False)
    full_name = db.Column(db.String)
    email = db.Column(db.String)
    phone = db.Column(db.String)
    duration = db.Column(db.String)
    department = db.Column(db.String)
    mentor = db.Column(db.String)
    mentor_name = db.Column(db.String)
    conversion_status = db.Column(db.String)
    conversion_potential = db.Column(db.String)
    status = db.Column(db.String)
    feedback = db.Column(db.String)
    education = db.Column(db.String)
    stipend = db.Column(db.Float)
    assigned_project = db.Column(db.String)
    internship_start_date = db.Column(db.Date)
    internship_end_date = db.Column(db.Date)
    monthly_salary_cost = db.Column(db.Float)
    billing_rate = db.Column(db.Float)
    monthly_revenue_generated = db.Column(db.Float)
    cost_center = db.Column(db.String)
    total_ytd_cost = db.Column(db.Float)
    total_ytd_revenue = db.Column(db.Float)
    utilization_rate = db.Column(db.Float)
    performance_rating = db.Column(db.Float)
    skills = db.Column(db.String)
    skillset = db.Column(db.String)
    performance_feedback = db.Column(db.String)
    status_detail = db.Column(db.String)
    # employee_ref = db.Column(db.Integer, db.ForeignKey('employees.id'))  # Disabled until employees table is confirmed
    bench_reason = db.Column(db.String)
    bench_aging_bucket = db.Column(db.String)
    bench_monthly_cost = db.Column(db.Float)
    bench_avg_daily_cost = db.Column(db.Float)
    bench_risk_level = db.Column(db.String)
    reallocation_opportunity = db.Column(db.Boolean)
    monthly_growth = db.Column(db.Float)
    department_data = db.Column(db.String)
    designation_data = db.Column(db.String)
    location_data = db.Column(db.String)
    monthly_growth_data = db.Column(db.String)
    summary_stats = db.Column(db.String)
    kpi_data = db.Column(db.String)
    productivity_score = db.Column(db.Float)
    client = db.Column(db.String)
    university = db.Column(db.String)
    start_date = db.Column(db.String)
    end_date = db.Column(db.String)
    location = db.Column(db.String)
    seniority_level = db.Column(db.String)
    is_intern = db.Column(db.Boolean)
