from sqlalchemy import Column, Integer, String, Float, ForeignKey, Date, Boolean
from .base import Base

class Intern(Base):
    name = Column(String, nullable=False)
    email = Column(String)
    university = Column(String)
    status = Column(String)
    start_date = Column(String)
    end_date = Column(String)
    conversion_status = Column(String)
    location = Column(String)
    __tablename__ = 'interns'
    id = Column(Integer, primary_key=True)
    employee_id = Column(String)
    name = Column(String, nullable=False)
    full_name = Column(String)
    duration = Column(String)
    department = Column(String)
    mentor = Column(String)
    mentor_name = Column(String)
    conversion_status = Column(String)
    conversion_potential = Column(String)
    status = Column(String)
    feedback = Column(String)
    education = Column(String)
    stipend = Column(Float)
    assigned_project = Column(String)
    internship_start_date = Column(Date)
    internship_end_date = Column(Date)
    monthly_salary_cost = Column(Float)
    billing_rate = Column(Float)
    monthly_revenue_generated = Column(Float)
    cost_center = Column(String)
    total_ytd_cost = Column(Float)
    total_ytd_revenue = Column(Float)
    utilization_rate = Column(Float)
    performance_rating = Column(Float)
    skills = Column(String)
    skillset = Column(String)
    performance_feedback = Column(String)
    status_detail = Column(String)
    # Relationships
    employee_ref = Column(Integer, ForeignKey('employees.id'))
    # Removed: employee = relationship('Employee')
    # Analytics & Management Fields
    bench_reason = Column(String)
    bench_aging_bucket = Column(String)
    bench_monthly_cost = Column(Float)
    bench_avg_daily_cost = Column(Float)
    bench_risk_level = Column(String)
    reallocation_opportunity = Column(Boolean)
    monthly_growth = Column(Float)
    department_data = Column(String)
    designation_data = Column(String)
    location_data = Column(String)
    monthly_growth_data = Column(String)
    summary_stats = Column(String)
    kpi_data = Column(String)
    productivity_score = Column(Float)
    client = Column(String)
    client_allocation = Column(String)
    utilization_trend = Column(String)
    performance_trend = Column(String)
    engagement_options = Column(String)
    engagement_notes = Column(String)
    release_date = Column(Date)
    role = Column(String)
    project_success_rate = Column(Float)
    performance_feedback_reviewer = Column(String)
    performance_feedback_date = Column(Date)
    performance_feedback_rating = Column(Float)
    performance_feedback_comment = Column(String)
    performance_feedback_strengths = Column(String)
    performance_feedback_improvements = Column(String)
    performance_feedback_goals = Column(String)
