from sqlalchemy import Column, Integer, String, Float, Date
from sqlalchemy.orm import relationship
from .base import Base

class Project(Base):
    __tablename__ = 'projects'
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(String)
    status = Column(String)
    priority = Column(String)
    budget = Column(Float)
    required_skills = Column(String)
    start_date = Column(Date)
    end_date = Column(Date)
    health_status = Column(String)
    profit_margin = Column(Float)
    utilization_rate = Column(Float)
    project_type = Column(String)
    client = Column(String)
    sow_value = Column(Float)
    billing_rate = Column(Float)
    actual_cost_to_date = Column(Float)
    billable_resources = Column(Integer)
    non_billable_resources = Column(Integer)
    shadow_resources = Column(Integer)
    monthly_burn = Column(Float)
    projected_completion = Column(String)
    net_position = Column(Float)
    margin = Column(Float)
    department = Column(String)
    team_size = Column(Integer)
    engineering_manager = Column(String)
    required_skills_list = Column(String)
    milestones = Column(String)
    risks = Column(String)
    kpis = Column(String)
    financial_summary = Column(String)
    resource_allocation = Column(String)
    engagement_plan = Column(String)
    status_detail = Column(String)
    priority_level = Column(String)
    velocity_trend = Column(String)
    code_coverage = Column(Float)
    performance_score = Column(Float)
    test_coverage = Column(Float)
    build_success_rate = Column(Float)
    deployment_frequency = Column(String)
    lead_time = Column(String)
    mttr = Column(String)
    technical_debt = Column(String)
    maintainability = Column(String)
    security_score = Column(Float)
    dependencies_updated = Column(String)
    category = Column(String)
    progress = Column(Integer)
    teamLead = Column(String)
