"""fix project relationships

Revision ID: 46a8443a835e
Revises: ebbbe5d8cfa3
Create Date: 2025-07-25 14:58:31.824830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a8443a835e'
down_revision = 'ebbbe5d8cfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'projects', ['project_id'], ['id'])
    op.drop_column('projects', 'milestones')
    op.drop_column('projects', 'risks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('risks', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('milestones', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'project_id')
    # ### end Alembic commands ###
