"""Initial migration

Revision ID: 540317659da7
Revises: fb7bdaa84a8a
Create Date: 2025-07-31 19:36:41.875147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540317659da7'
down_revision = 'fb7bdaa84a8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('employee_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('employee_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
