"""Add fields for team member seeding

Revision ID: 665207ec972f
Revises: e1767a6de612
Create Date: 2025-07-25 16:14:23.189705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665207ec972f'
down_revision = 'e1767a6de612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('experience', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('allocation', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('performance', sa.String(), nullable=True))
    op.alter_column('employees', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('employees', 'performance')
    op.drop_column('employees', 'allocation')
    op.drop_column('employees', 'experience')
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###
