"""Update Resource model to match frontend fields

Revision ID: 98261f0ec70a
Revises: 7041e0f31025
Create Date: 2025-07-28 00:01:52.113631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98261f0ec70a'
down_revision = '7041e0f31025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
