"""fix project relationships

Revision ID: cd5fd52602f1
Revises: 46a8443a835e
Create Date: 2025-07-25 15:02:56.987706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5fd52602f1'
down_revision = '46a8443a835e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
