"""fix escalation model fields to snake_case only

Revision ID: d7ca240c39c6
Revises: c230fabc861e
Create Date: 2025-07-25 13:32:04.932857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ca240c39c6'
down_revision = 'c230fabc861e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escalations', sa.Column('risk_level', sa.String(), nullable=True))
    op.alter_column('escalations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('escalations', 'riskLevel')
    op.drop_column('escalations', 'resolutionETA')
    op.drop_column('escalations', 'dateRaised')
    op.alter_column('kpis', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('risks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('risks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('kpis', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('escalations', sa.Column('dateRaised', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('escalations', sa.Column('resolutionETA', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('escalations', sa.Column('riskLevel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('escalations', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('escalations', 'risk_level')
    # ### end Alembic commands ###
