"""empty message

Revision ID: db557d436e68
Revises: 540317659da7
Create Date: 2025-08-01 11:09:31.149286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db557d436e68'
down_revision = '540317659da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sprint_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('velocity', sa.Float(), nullable=True),
    sa.Column('predictability', sa.Float(), nullable=True),
    sa.Column('defect_leakage', sa.Float(), nullable=True),
    sa.Column('on_time_delivery', sa.Float(), nullable=True),
    sa.Column('planned_story_points', sa.Integer(), nullable=True),
    sa.Column('completed_story_points', sa.Integer(), nullable=True),
    sa.Column('test_cases_executed', sa.Integer(), nullable=True),
    sa.Column('test_cases_passed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprints')
    # ### end Alembic commands ###
