"""set escalation id autoincrement true

Revision ID: dde9273e618d
Revises: d7ca240c39c6
Create Date: 2025-07-25 13:39:10.414383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde9273e618d'
down_revision = 'd7ca240c39c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
