"""add teams and engineering_metrics to project

Revision ID: e1767a6de612
Revises: cd5fd52602f1
Create Date: 2025-07-25 15:07:51.671570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1767a6de612'
down_revision = 'cd5fd52602f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('teams', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('engineering_metrics', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'engineering_metrics')
    op.drop_column('projects', 'teams')
    # ### end Alembic commands ###
