"""add all escalation fields to model

Revision ID: ebbbe5d8cfa3
Revises: dde9273e618d
Create Date: 2025-07-25 13:54:25.029801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbbe5d8cfa3'
down_revision = 'dde9273e618d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
