"""Align models with all frontend fields

Revision ID: f52e87dfc158
Revises: 77b93ceb64ef
Create Date: 2025-07-25 11:30:14.218289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52e87dfc158'
down_revision = '77b93ceb64ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('utilization_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_project_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('primary_skills', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secondary_skills', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bench_start_date', sa.Date(), nullable=True))

    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_raised', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resolution_eta', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dateRaised', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('resolutionETA', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('riskLevel', sa.String(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('resolutioneta')
        batch_op.drop_column('dateraised')
        batch_op.drop_column('risklevel')

    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('project_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('client', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.String(), nullable=True))

    with op.batch_alter_table('interns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('university', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))

    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('target', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.String(), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_lead', sa.String(), nullable=True))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilization_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_project_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('primary_skills', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('secondary_skills', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bench_start_date', sa.Date(), nullable=True))
        batch_op.drop_column('currentproject')
        batch_op.drop_column('billable')
        batch_op.drop_column('nonbillable')
        batch_op.drop_column('allocation')
        batch_op.drop_column('utilization')

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('likelihood', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_column('likelihood')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilization', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allocation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nonbillable', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('billable', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currentproject', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('bench_start_date')
        batch_op.drop_column('secondary_skills')
        batch_op.drop_column('primary_skills')
        batch_op.drop_column('last_project_end_date')
        batch_op.drop_column('utilization_percentage')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('team_lead')

    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_column('due_date')
        batch_op.drop_column('description')

    with op.batch_alter_table('kpis', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('status')
        batch_op.drop_column('target')
        batch_op.drop_column('name')

    with op.batch_alter_table('interns', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('university')
        batch_op.drop_column('email')

    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('client')
        batch_op.drop_column('project_type')
        batch_op.drop_column('project_name')

    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risklevel', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dateraised', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('resolutioneta', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('riskLevel')
        batch_op.drop_column('resolutionETA')
        batch_op.drop_column('dateRaised')
        batch_op.drop_column('resolution_eta')
        batch_op.drop_column('date_raised')

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('bench_start_date')
        batch_op.drop_column('secondary_skills')
        batch_op.drop_column('primary_skills')
        batch_op.drop_column('last_project_end_date')
        batch_op.drop_column('utilization_percentage')
        batch_op.drop_column('experience_level')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
